{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "sd-prometheus.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "sd-prometheus.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "sd-prometheus.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
{{- end -}}
